# Generated by Django 5.0.7 on 2024-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_location_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
