# Generated by Django 5.0.1 on 2024-08-07 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_booking_uid'),
        ('organizer', '0005_organizer_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='oid',
            field=models.ForeignKey(db_column='oid', default=1, on_delete=django.db.models.deletion.CASCADE, to='organizer.organizer'),
            preserve_default=False,
        ),
    ]
