# Generated by Django 5.0.1 on 2024-08-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_booking_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='oid',
        ),
    ]
