# Generated by Django 5.0.1 on 2024-08-09 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_booking_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='oid',
        ),
    ]
