# Generated by Django 5.0.1 on 2024-08-09 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_booking_oid'),
        ('event', '0009_alter_event_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='uid',
        ),
        migrations.AddField(
            model_name='booking',
            name='eid',
            field=models.ForeignKey(db_column='eid', default=1, on_delete=django.db.models.deletion.CASCADE, to='event.event'),
            preserve_default=False,
        ),
    ]
