# Generated by Django 5.0.6 on 2024-07-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='date',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
