# Generated by Django 5.0.1 on 2024-07-30 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_remove_organizer_date_alter_organizer_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='title',
            new_name='Name',
        ),
    ]
