# Generated by Django 5.0.1 on 2024-07-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_rename_title_organizer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='Name',
            new_name='name',
        ),
    ]
