# Generated by Django 5.0.1 on 2024-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_bookedby_event_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventdescription',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventlocation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
