# Generated by Django 5.0.1 on 2024-07-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_eventdescription_event_eventlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
    ]
