# Generated by Django 5.0.1 on 2024-07-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_event_bookedby_event_category'),
        ('organizer', '0004_rename_name_organizer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='createdby',
        ),
        migrations.AddField(
            model_name='event',
            name='oid',
            field=models.ForeignKey(db_column='oid', default=1, on_delete=django.db.models.deletion.CASCADE, to='organizer.organizer'),
            preserve_default=False,
        ),
    ]
